name: Test Access

on:
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Test API access
        run: |
          curl -H "Authorization: token ${{ secrets.GH_TOKEN }}" \
               https://api.github.com/repos/<org>/<private-repo>/contents/
