name: Get Project Info (Temporário)

on:
  workflow_dispatch:

jobs:
  get-info:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.PROJECT_TOKEN }}
          script: |
            const projectId = "PVT_kwDODixzhM4BFb_a";
            
            const query = `
              query ($projectId: ID!) {
                node(id: $projectId) {
                  ... on ProjectV2 {
                    title
                    fields(first: 20) {
                      nodes {
                        ... on ProjectV2SingleSelectField {
                          id
                          name
                          options {
                            id
                            name
                          }
                        }
                      }
                    }
                  }
                }
              }
            `;
            
            const result = await github.graphql(query, { projectId });
            
            console.log("📊 Informações do Projeto:");
            console.log(JSON.stringify(result, null, 2));
            
            // Procura pelo campo de status
            const statusField = result.node.fields.nodes.find(f => 
              f.id === "PVTSSF_lADODixzhM4BFb_azg2xh6E"
            );
            
            if (statusField) {
              console.log("\n✅ Status disponíveis:");
              statusField.options.forEach(opt => {
                console.log(`   ${opt.name}: ${opt.id}`);
              });
            }
