name: Sync Issues to Target Repo

on:
  issues:
    types: [labeled]

jobs:
  sync:
    runs-on: ubuntu-latest
    if: github.event.action == 'opened' || github.event.action == 'labeled'

    steps:
      - name: Extract data
        id: extract
        run: |
          echo "title<<EOF" >> $GITHUB_OUTPUT
          echo "${{ github.event.issue.title }}" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
          
          echo "body<<EOF" >> $GITHUB_OUTPUT
          echo "${{ github.event.issue.body }}" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Determine target repo from label
        id: target
        run: |
          echo "Detectando label..."
          LABEL_NAME="${{ github.event.label.name }}"
          
          if [ -z "$LABEL_NAME" ]; then
            echo "Nenhuma label no evento direto, tentando pegar a primeira label da issue..."
            LABEL_NAME=$(echo "${{ github.event.issue.labels[0].name }}" | tr -d '[:space:]')
          fi

          if [ -z "$LABEL_NAME" ]; then
            echo "Nenhuma label encontrada. Encerrando."
            exit 1
          fi

          echo "repo=$LABEL_NAME" >> $GITHUB_OUTPUT
          echo "Repositório alvo: $LABEL_NAME"

      - name: Create issue in target repository
        run: |
          echo "Criando issue em Ambiente-de-Testes/${{ steps.target.outputs.repo }}..."
          RESPONSE=$(curl -s -o response.json -w "%{http_code}" -X POST \
            -H "Authorization: token ${{ secrets.GH_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/Ambiente-de-Testes/${{ steps.target.outputs.repo }}/issues \
            -d @- <<EOF
          {
            "title": "${{ steps.extract.outputs.title }}",
            "body": "${{ steps.extract.outputs.body }}\n\n---\n_Origin: https://github.com/${{ github.repository }}/issues/${{ github.event.issue.number }}_"
          }
          EOF
          )

          echo "Código de resposta: $RESPONSE"
          cat response.json
          if [ "$RESPONSE" -ne 201 ]; then
            echo "Falha ao criar a issue."
            exit 1
          fi
