name: Update Issues - Central

on:
  repository_dispatch:
    types: [branch_created]

jobs:
  update-project:
    runs-on: ubuntu-latest
    steps:
      - name: Log evento recebido
        run: |
          echo "📡 Evento recebido de outro repositório"
          echo "   Repositório: ${{ github.event.client_payload.repository }}"
          echo "   Branch: ${{ github.event.client_payload.branch }}"
          echo "   Issue: #${{ github.event.client_payload.issue_number }}"
          
      - uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.UPDATE_TOKEN }}
          script: |
            const projectId = "PVT_kwDODixzhM4BFb_a";
            const statusFieldId = "PVTSSF_lADODixzhM4BFb_azg2xh6E";
            const STATUS_EM_DESENVOLVIMENTO = "823324b0";
            
            // Dados vindos do outro repositório
            const payload = context.payload.client_payload;
            const issueNumber = payload.issue_number;
            const repoFullName = payload.repository;
            const [owner, repo] = repoFullName.split('/');
            
            console.log(`🔍 Processando issue #${issueNumber} de ${owner}/${repo}`);
            
            try {
              // Busca a issue no repositório de origem
              const { data: issue } = await github.rest.issues.get({
                owner: owner,
                repo: repo,
                issue_number: issueNumber
              });
              
              console.log(`✅ Issue encontrada: #${issue.number} - ${issue.title}`);
              const issueNodeId = issue.node_id;
              
              // Busca no projeto
              const projectQuery = `
                query ($projectId: ID!) {
                  node(id: $projectId) {
                    ... on ProjectV2 {
                      title
                      items(first: 100) {
                        nodes {
                          id
                          content {
                            ... on Issue { id number title }
                            ... on PullRequest { id number title }
                          }
                        }
                      }
                    }
                  }
                }
              `;
              
              const projectData = await github.graphql(projectQuery, { projectId });
              const items = projectData.node.items.nodes;
              const projectItem = items.find(i => i.content?.id === issueNodeId);
              
              if (!projectItem) {
                console.log(`⚠️ Issue #${issueNumber} não está no projeto`);
                return;
              }
              
              console.log(`✅ Item encontrado no projeto`);
              
              // Atualiza status
              const updateMutation = `
                mutation ($projectId: ID!, $itemId: ID!, $fieldId: ID!, $value: String!) {
                  updateProjectV2ItemFieldValue(input: {
                    projectId: $projectId
                    itemId: $itemId
                    fieldId: $fieldId
                    value: { singleSelectOptionId: $value }
                  }) {
                    projectV2Item { id }
                  }
                }
              `;
              
              await github.graphql(updateMutation, {
                projectId,
                itemId: projectItem.id,
                fieldId: statusFieldId,
                value: STATUS_EM_DESENVOLVIMENTO
              });
              
              console.log(`🎉 Issue #${issueNumber} movida para "Em Desenvolvimento"!`);
              
            } catch (error) {
              console.error(`❌ Erro: ${error.message}`);
              throw error;
            }
