name: Update Issues on Private Repos

on:
  issues:
    types: [opened, closed]
  pull_request:
    types: [opened, closed]
  create:
    branches:
      - '**'

jobs:
  update-project:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const projectId = "PVT_kwDODixzhM4BFb_a"; // ID do ProjectV2
            const statusFieldId = "PVTSSF_lADODixzhM4BFb_azg2xh6E"; // ID do campo de Status
            const org = "Ambiente-de-Testes"; // nome exato da organização

            async function moveIssueToStatus(itemId, statusName) {
              const mutation = `
                mutation ($projectId: ID!, $itemId: ID!, $statusFieldId: ID!, $statusName: String!) {
                  updateProjectV2ItemFieldValue(input: {
                    projectId: $projectId
                    itemId: $itemId
                    fieldId: $statusFieldId
                    value: { singleSelectOptionName: $statusName }
                  }) {
                    projectV2Item { id }
                  }
                }
              `;
              await github.graphql(mutation, { projectId, itemId, statusFieldId, statusName });
            }

            async function getProjectItemId(issueNodeId) {
              const query = `
                query ($org: String!, $projectId: ID!) {
                  organization(login: $org) {
                    projectV2(id: $projectId) {
                      items(first: 100) {
                        nodes {
                          id
                          content {
                            ... on Issue { id number }
                            ... on PullRequest { id number }
                          }
                        }
                      }
                    }
                  }
                }
              `;
              const res = await github.graphql(query, { org, projectId });
              const items = res.organization.projectV2.items.nodes;
              const item = items.find(i => i.content?.id === issueNodeId);
              return item?.id;
            }

            // Identifica o tipo de evento e pega o Node ID
            let issueNodeId;
            if (context.payload.issue) {
              issueNodeId = context.payload.issue.node_id;
            } else if (context.payload.pull_request) {
              issueNodeId = context.payload.pull_request.node_id;
            } else {
              console.log("Evento não relacionado a issue ou PR.");
              return;
            }

            const itemId = await getProjectItemId(issueNodeId);
            if (!itemId) {
              console.log("Item não encontrado no projeto.");
              return;
            }

            // Lógica de automação
            if (context.eventName === "issues" && context.payload.action === "opened") {
              await moveIssueToStatus(itemId, "Não Iniciado");
            }

            if (context.eventName === "create") {
              await moveIssueToStatus(itemId, "Em Desenvolvimento");
            }

            if (context.eventName === "issues" && context.payload.action === "closed") {
              await moveIssueToStatus(itemId, "Em Testes");
            }

            if (context.eventName === "pull_request" && context.payload.action === "opened") {
              await moveIssueToStatus(itemId, "Aguardando Atualização");
            }

            if (context.eventName === "pull_request" && context.payload.action === "closed" && context.payload.pull_request.merged) {
              await moveIssueToStatus(itemId, "Atualizado (Concluído)");
            }

            console.log("Status atualizado com sucesso!");
