name: Atualizar Issue ao Criar Branch

on:
  create:
    branches:
      - "*"

jobs:
  update-issue:
    runs-on: ubuntu-latest

    steps:
      - name: Rodar script do GitHub
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const branchName = process.env.GITHUB_REF.replace('refs/heads/', '');
            console.log(`Nova branch criada: ${branchName}`);

            // Extrai o número da issue do nome da branch
            const match = branchName.match(/^(\d+)-/);
            if (!match) {
              console.log('❌ Nenhum número de issue encontrado na branch.');
              return;
            }

            const issueNumber = parseInt(match[1]);
            console.log(`Número da issue detectado: ${issueNumber}`);

            const org = 'Ambiente-de-Testes';
            const repo = 'Repo-Test-DevOps';

            // Busca a issue pelo número via GraphQL
            const query = `
              query ($org: String!, $repo: String!, $issueNumber: Int!) {
                organization(login: $org) {
                  repository(name: $repo) {
                    issue(number: $issueNumber) {
                      id
                      title
                      number
                    }
                  }
                }
              }
            `;

            const result = await github.graphql(query, {
              org,
              repo,
              issueNumber
            });

            const issue = result.organization.repository.issue;
            if (!issue) {
              console.log('⚠️ Nenhuma issue encontrada para esse número.');
              return;
            }

            console.log(`✅ Issue encontrada: #${issue.number} - ${issue.title}`);
            console.log(`🆔 ID interno: ${issue.id}`);

            // Exemplo: atualizar Project ou Status da issue
            // const projectId = "PVT_kwDODixzhM4BFb_a";
            // const statusFieldId = "PVTSSF_lADODixzhM4BFb_azg2xh6E";
            // await github.graphql(
            //   `
            //     mutation($projectId: ID!, $issueId: ID!, $statusFieldId: ID!, $value: String!) {
            //       updateProjectV2ItemFieldValue(
            //         input: {
            //           projectId: $projectId
            //           itemId: $issueId
            //           fieldId: $statusFieldId
            //           value: { singleSelectOptionId: $value }
            //         }
            //       ) {
            //         projectV2Item {
            //           id
            //         }
            //       }
            //     }
            //   `,
            //   {
            //     projectId,
            //     issueId: issue.id,
            //     statusFieldId,
            //     value: "TO_DO"
            //   }
            // );

            console.log('🚀 Script concluído com sucesso!');
