name: Atualizar issue e project ao criar branch

on:
  push:
    branches:
      - '**'

jobs:
  update_issue_project:
    runs-on: ubuntu-latest
    steps:
      - name: Checar branch
        run: echo "Branch: ${{ github.ref_name }}"

      - name: Listar opções do campo Status
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GH_TOKEN }}
          script: |
            const projectId = "PVT_kwDODixzhM4BFb_a";
            const statusFieldId = "PVTSSF_lADODixzhM4BFb_azg2xh6E";

            const result = await github.graphql(`
              query ($projectId: ID!, $fieldId: ID!) {
                node(id: $projectId) {
                  ... on ProjectV2 {
                    field(id: $fieldId) {
                      ... on ProjectV2SingleSelectField {
                        name
                        options {
                          id
                          name
                        }
                      }
                    }
                  }
                }
              }
            `, { projectId, fieldId: statusFieldId });

            console.log("🧩 Opções do campo:", JSON.stringify(result, null, 2));
