name: Atualizar issue e project ao criar branch

on:
  create:
    branches:
      - "*"

jobs:
  update_issue_project:
    runs-on: ubuntu-latest

    steps:
      - name: Verificar nome da branch
        id: extract_number
        run: |
          echo "Branch criada: ${{ github.ref_name }}"
          BRANCH_NAME="${{ github.ref_name }}"
          ISSUE_NUMBER=$(echo "$BRANCH_NAME" | grep -oE '^[0-9]+')
          if [ -z "$ISSUE_NUMBER" ]; then
            echo "Nenhum número de issue encontrado no nome da branch."
            exit 0
          fi
          echo "Número da issue detectado: $ISSUE_NUMBER"
          echo "issue_number=$ISSUE_NUMBER" >> $GITHUB_OUTPUT

      - name: Atualizar issue no Project
        if: steps.extract_number.outputs.issue_number != ''
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GH_TOKEN }}
          script: |
            console.log("🚀 Versão do workflow: 2025-10-13 sem node_id ✅");

            const issueNumber = parseInt("${{ steps.extract_number.outputs.issue_number }}");
            const [owner, repo] = process.env.GITHUB_REPOSITORY.split("/");

            console.log("Repositório:", owner + "/" + repo);
            console.log("Issue detectada:", issueNumber);

            // Busca os dados da issue
            const query = `
              query ($owner: String!, $repo: String!, $issueNumber: Int!) {
                repository(owner: $owner, name: $repo) {
                  issue(number: $issueNumber) {
                    id
                    title
                    number
                  }
                }
              }
            `;

            const result = await github.graphql(query, { owner, repo, issueNumber });
            const issue = result.repository.issue;

            if (!issue) {
              console.log("❌ Nenhuma issue encontrada com esse número.");
              return;
            }

            console.log(`✅ Issue encontrada: #${issue.number} - ${issue.title}`);

            // IDs fixos (ajuste conforme seu Project)
            const projectId = "PVT_kwDODixzhM4BFb_a";
            const statusFieldId = "PVTSSF_lADODixzhM4BFb_azg2xh6E";
            const statusValueId = "f6161a93"; // Exemplo de valor para "Em andamento"

            // Encontra o item do Project referente à issue
            const projectItems = await github.graphql(`
              query ($projectId: ID!) {
                node(id: $projectId) {
                  ... on ProjectV2 {
                    items(first: 50) {
                      nodes {
                        id
                        content {
                          ... on Issue {
                            id
                            number
                          }
                        }
                      }
                    }
                  }
                }
              }
            `, { projectId });

            const item = projectItems.node.items.nodes.find(
              (n) => n.content && n.content.number === issue.number
            );

            if (!item) {
              console.log("❌ Nenhum item correspondente à issue encontrado no Project.");
              return;
            }

            console.log(`🧩 Item encontrado no Project: ${item.id}`);

            // Atualiza o campo de Status
            await github.graphql(`
              mutation ($projectId: ID!, $itemId: ID!, $fieldId: ID!, $valueId: String!) {
                updateProjectV2ItemFieldValue(
                  input: {
                    projectId: $projectId
                    itemId: $itemId
                    fieldId: $fieldId
                    value: { singleSelectOptionId: $valueId }
                  }
                ) {
                  projectV2Item {
                    id
                  }
                }
              }
            `, {
              projectId,
              itemId: item.id,
              fieldId: statusFieldId,
              valueId: statusValueId
            });

            console.log("✅ Status atualizado com sucesso no Project!");
